import { parseInkSource, type InkKnot } from './inkParser'
import { escapeHtml } from '../../../shared/storyExport'

/**
 * Generate a PDF walkthrough of all story paths.
 * Uses the browser's print API to produce a PDF from a generated HTML document.
 */
export function generateWalkthroughHTML(inkSource: string, title: string): string {
  const parsed = parseInkSource(inkSource)
  const startKnot = parsed.topLevelDivert || parsed.knots[0]?.id || 'start'

  // Build adjacency map
  const knotMap = new Map<string, InkKnot>()
  for (const knot of parsed.knots) {
    knotMap.set(knot.id, knot)
  }

  // Traverse all paths (BFS with depth limit to avoid infinite loops)
  const paths: { nodes: string[]; ending: string | null }[] = []
  const MAX_DEPTH = 50

  function traverse(knotId: string, path: string[], visited: Set<string>) {
    if (path.length > MAX_DEPTH) return
    if (visited.has(knotId)) {
      paths.push({ nodes: [...path, `(loop: ${knotId})`], ending: null })
      return
    }

    const knot = knotMap.get(knotId)
    if (!knot) {
      paths.push({ nodes: path, ending: null })
      return
    }

    const newPath = [...path, knotId]
    const newVisited = new Set(visited)
    newVisited.add(knotId)

    if (knot.choices.length === 0) {
      paths.push({ nodes: newPath, ending: knot.endingType })
      return
    }

    for (const choice of knot.choices) {
      if (choice.target && choice.target !== 'END' && choice.target !== 'DONE') {
        traverse(choice.target, newPath, newVisited)
      } else {
        paths.push({ nodes: newPath, ending: knot.endingType })
      }
    }
  }

  traverse(startKnot, [], new Set())

  // Generate HTML
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${escapeHtml(title)} — Story Walkthrough</title>
<style>
  body {
    font-family: Georgia, serif;
    max-width: 800px;
    margin: 40px auto;
    padding: 0 20px;
    color: #333;
    line-height: 1.6;
  }
  h1 { font-size: 24px; margin-bottom: 8px; }
  h2 { font-size: 18px; color: #666; margin-top: 32px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
  h3 { font-size: 15px; color: #444; margin-top: 16px; }
  .meta { color: #888; font-size: 14px; margin-bottom: 24px; }
  .passage { margin: 12px 0; padding: 12px 16px; background: #f8f8f8; border-left: 3px solid #7c6ef0; border-radius: 4px; }
  .passage-title { font-weight: bold; font-size: 14px; color: #7c6ef0; }
  .passage-content { font-size: 14px; margin-top: 4px; }
  .choice { color: #7c6ef0; font-weight: 600; font-size: 13px; margin-top: 4px; }
  .ending { font-weight: bold; text-transform: uppercase; font-size: 12px; padding: 4px 8px; border-radius: 4px; display: inline-block; margin-top: 8px; }
  .ending.good { background: #e8f5e9; color: #2e7d32; }
  .ending.neutral { background: #fff8e1; color: #f57f17; }
  .ending.bad { background: #ffebee; color: #c62828; }
  .path-label { font-size: 13px; color: #888; margin-bottom: 8px; }
  .vars { font-size: 12px; color: #666; font-family: monospace; margin-top: 16px; }
  @media print {
    .passage { break-inside: avoid; }
  }
</style>
</head>
<body>
<h1>${escapeHtml(title)}</h1>
<div class="meta">
  ${parsed.knots.length} passages &middot; ${paths.length} paths &middot; ${parsed.variables.length} variables
</div>

${parsed.variables.length > 0 ? `
<div class="vars">
  <strong>Variables:</strong> ${parsed.variables.map(v => `${v.name} = ${v.initialValue}`).join(', ')}
</div>
` : ''}

<h2>All Story Paths</h2>

${paths.map((path, i) => `
<h3>Path ${i + 1}${path.ending ? ` — ${escapeHtml(path.ending)} ending` : ''}</h3>
<div class="path-label">${path.nodes.join(' → ')}</div>
${path.nodes.map(nodeId => {
  const knot = knotMap.get(nodeId)
  if (!knot) return `<div class="passage"><div class="passage-title">${escapeHtml(nodeId)}</div></div>`
  return `
<div class="passage">
  <div class="passage-title">${escapeHtml(knot.title)}</div>
  <div class="passage-content">${escapeHtml(knot.content.substring(0, 200))}${knot.content.length > 200 ? '...' : ''}</div>
  ${knot.choices.map(c => `<div class="choice">→ ${escapeHtml(c.text)}</div>`).join('')}
</div>`
}).join('')}
${path.ending ? `<span class="ending ${escapeHtml(path.ending)}">${escapeHtml(path.ending)} ending</span>` : ''}
`).join('\n')}

<h2>All Passages (Reference)</h2>
${parsed.knots.map(knot => `
<div class="passage">
  <div class="passage-title">${escapeHtml(knot.title)}</div>
  <div class="passage-content">${escapeHtml(knot.content)}</div>
  ${knot.choices.map(c => `<div class="choice">→ ${escapeHtml(c.text)} → ${escapeHtml(c.target)}</div>`).join('')}
  ${knot.endingType ? `<span class="ending ${escapeHtml(knot.endingType)}">${escapeHtml(knot.endingType)} ending</span>` : ''}
</div>
`).join('')}

<div style="text-align: center; color: #888; font-size: 12px; margin-top: 48px;">
  Generated by Playable Lessons
</div>
</body>
</html>`
}
