// Generates src/shared/version.generated.ts from the root package.json, so the
// CLI's --version (and anything else) has a single source of truth.
//
// Regenerated by `npm run build:cli` (and therefore by `prepublishOnly` before
// every publish). Run it manually after a bump for local dev:  npm run embed:version
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const pkgPath = join(here, '..', 'package.json')
const version = JSON.parse(readFileSync(pkgPath, 'utf8')).version

const out = `// AUTO-GENERATED by scripts/embed-version.mjs — do not edit by hand.
// Source: package.json (version). Regenerate: npm run embed:version
/* eslint-disable */
export const APP_VERSION = ${JSON.stringify(version)}
`

const target = join(here, '..', 'src', 'shared', 'version.generated.ts')
writeFileSync(target, out, 'utf8')
console.log(`Wrote APP_VERSION = ${version} -> ${target}`)
